apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: main-keycloak
  namespace: keycloak
spec:
  instances: 1 # replica count
  
  db:
    vendor: postgres
    host: postgres-db.keycloak.svc.cluster.local # db adress
    database: keycloak
    port: 5432
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password

  http:
    httpEnabled: true 
    httpPort: 8080

  hostname:
    hostname: https://static92.com # domain for client
    admin: https://static92.com # domain for admin

  additionalOptions:
    - name: bootstrap-admin-username
      value: "admin"
    - name: bootstrap-admin-password
      value: "MySuperSecurePassword123"  
    - name: proxy-headers
      value: "xforwarded"
    - name: log-level
      value: "info"
    - name: metrics-enabled
      value: "true"

  podTemplate:
    spec:
      containers:
        - name: keycloak
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
