apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: my-minio-storage
  namespace: minio
spec:
  image: quay.io/minio/minio:RELEASE.2025-04-08T15-41-24Z 
  configuration:
    name: storage-configuration

  pools:
    - name: pool-0
      servers: 4
      volumesPerServer: 4
      
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: local-hostpath 

  #     # Prod
  #     resources:
  #       requests:
  #         cpu: "4"
  #         memory: "8Gi"
  #       limits:
  #         cpu: "4"
  #         memory: "8Gi"

  #     affinity:
  #       podAntiAffinity:
  #         requiredDuringSchedulingIgnoredDuringExecution:
  #           - labelSelector:
  #               matchExpressions:
  #                 - key: v1.min.io/tenant
  #                   operator: In
  #                   values:
  #                     - my-minio-storage
  #             topologyKey: kubernetes.io/hostname

  # requestAutoCert: true
