apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio
  annotations:

    nginx.ingress.kubernetes.io/proxy-body-size: "0" # allow any size files
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600" # timeout for big files
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - s3.static92minio.com
        - console.static92minio.com
      secretName: minio-external-tls-secret
  rules:
    # S3 API
    - host: s3.static92minio.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio 
                port:
                  number: 9000      
    # Web Console
    - host: console.static92minio.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-minio-storage-console 
                port:
                  number: 9443 


