apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vm-agent
  namespace: victoria-metrics
spec:
  serviceAccountName: vm-agent-sa
  replicaCount: 1
  
  remoteWrite:
    - url: "http://vmsingle-vm-database:8428" # vm base

  # scrape all
  serviceScrapeSelector: {}
  podScrapeSelector: {}
  nodeScrapeSelector: {}
  staticScrapeSelector: {}

  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-agent-sa
  namespace: victoria-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-agent-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/metrics", "services", "endpoints", "pods", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
    verbs: ["get"]
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubernetes-kubelet-scrape
  namespace: victoria-metrics
spec:
  path: /metrics
  scheme: https
  tlsConfig:
    insecureSkipVerify: true
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  interval: 15s
