apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4" # fourh
spec:
  project: default
  source:
    repoURL: 'https://github.com/static92/k8s.git'
    targetRevision: main
    path: k8s/core/ingress-nginx # local path
  destination:
    server: 'https://default.svc'
    namespace: ingress-nginx
  syncPolicy:
    createNamespace: true
    automated:
      prune: true
      selfHeal: true
