apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # first in row
spec:
  project: default
  source:
    repoURL: 'https://github.com/static92/k8s.git'
    targetRevision: main
    path: k8s/core/metallb # local path
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  syncPolicy:
    createNamespace: true
    automated:
      prune: true
      selfHeal: true
