---
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-service
  namespace: elastic-system
spec:
  version: 9.5.0
  count: 1
  elasticsearchRefs:
    - name: elastic
      clusterName: elastic
  config:
    allow_superuser: true
  podTemplate:
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
  volumeClaimTemplates:
    - metadata:
        name: logstash-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-hostpath" # not replicate
        resources:
          requests:
            storage: 2Gi
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats { 
            port => 5044
          }
        }
        filter {
          mutate { add_field => { "cluster_type" => "microk8s-3node-official-eck3" } }
        }
        output {
          elasticsearch {
            hosts => [ "${ELASTIC_ES_HOSTS}" ]
            user => "${ELASTIC_ES_USER}"
            password => "${ELASTIC_ES_PASSWORD}"
            ssl_certificate_authorities => "${ELASTIC_ES_SSL_CERTIFICATE_AUTHORITY}"
          }
        }
 
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-service-beats
  namespace: elastic-system
spec:
  selector:
    logstash.k8s.elastic.co/name: logstash-service # elc label
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
  type: ClusterIP