apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: elastic-system
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  version: 9.5.0
  nodeSets:
  - name: default
    count: 1
    config:
      # official roles
      node.roles:  ["master", "data_content", "data_hot", "ingest"]
      node.store.allow_mmap: true
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 100Mi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 2
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: local-hostpath # replicate
